[package]
name = "wikiup"
version = "0.1.0"
edition = "2021"

[dependencies]
markdown = { path = "crates/markdown" }
util = { path = "crates/util" }
server = { path = "crates/server" }

[workspace]
members = [
    "crates/markdown",
    "crates/util",
    "crates/server",
]
